// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: src/proto/negotiation/negotiation.proto

package negotiation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subsegment_Type int32

const (
	Subsegment_LINK      Subsegment_Type = 0
	Subsegment_REFERENCE Subsegment_Type = 1
)

// Enum value maps for Subsegment_Type.
var (
	Subsegment_Type_name = map[int32]string{
		0: "LINK",
		1: "REFERENCE",
	}
	Subsegment_Type_value = map[string]int32{
		"LINK":      0,
		"REFERENCE": 1,
	}
)

func (x Subsegment_Type) Enum() *Subsegment_Type {
	p := new(Subsegment_Type)
	*p = x
	return p
}

func (x Subsegment_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Subsegment_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_negotiation_negotiation_proto_enumTypes[0].Descriptor()
}

func (Subsegment_Type) Type() protoreflect.EnumType {
	return &file_src_proto_negotiation_negotiation_proto_enumTypes[0]
}

func (x Subsegment_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Subsegment_Type.Descriptor instead.
func (Subsegment_Type) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{6, 0}
}

type NegotiationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegmentSets []*ClientSegmentSet `protobuf:"bytes,1,rep,name=segment_sets,json=segmentSets,proto3" json:"segment_sets,omitempty"`
}

func (x *NegotiationRequest) Reset() {
	*x = NegotiationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiationRequest) ProtoMessage() {}

func (x *NegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiationRequest.ProtoReflect.Descriptor instead.
func (*NegotiationRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{0}
}

func (x *NegotiationRequest) GetSegmentSets() []*ClientSegmentSet {
	if x != nil {
		return x.SegmentSets
	}
	return nil
}

type NegotiationReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegmentSets []*ServerSegmentSet `protobuf:"bytes,1,rep,name=segment_sets,json=segmentSets,proto3" json:"segment_sets,omitempty"` // TODO: add utility description
}

func (x *NegotiationReply) Reset() {
	*x = NegotiationReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NegotiationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiationReply) ProtoMessage() {}

func (x *NegotiationReply) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiationReply.ProtoReflect.Descriptor instead.
func (*NegotiationReply) Descriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{1}
}

func (x *NegotiationReply) GetSegmentSets() []*ServerSegmentSet {
	if x != nil {
		return x.SegmentSets
	}
	return nil
}

type ClientSegmentSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetId              uint32           `protobuf:"varint,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	CompatibleNextSets []uint32         `protobuf:"varint,2,rep,packed,name=compatible_next_sets,json=compatibleNextSets,proto3" json:"compatible_next_sets,omitempty"`
	Segments           []*ClientSegment `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *ClientSegmentSet) Reset() {
	*x = ClientSegmentSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSegmentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSegmentSet) ProtoMessage() {}

func (x *ClientSegmentSet) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSegmentSet.ProtoReflect.Descriptor instead.
func (*ClientSegmentSet) Descriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{2}
}

func (x *ClientSegmentSet) GetSetId() uint32 {
	if x != nil {
		return x.SetId
	}
	return 0
}

func (x *ClientSegmentSet) GetCompatibleNextSets() []uint32 {
	if x != nil {
		return x.CompatibleNextSets
	}
	return nil
}

func (x *ClientSegmentSet) GetSegments() []*ClientSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type ServerSegmentSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetId              uint32           `protobuf:"varint,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	CompatibleNextSets []uint32         `protobuf:"varint,2,rep,packed,name=compatible_next_sets,json=compatibleNextSets,proto3" json:"compatible_next_sets,omitempty"`
	Segments           []*ServerSegment `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *ServerSegmentSet) Reset() {
	*x = ServerSegmentSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSegmentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSegmentSet) ProtoMessage() {}

func (x *ServerSegmentSet) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSegmentSet.ProtoReflect.Descriptor instead.
func (*ServerSegmentSet) Descriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{3}
}

func (x *ServerSegmentSet) GetSetId() uint32 {
	if x != nil {
		return x.SetId
	}
	return 0
}

func (x *ServerSegmentSet) GetCompatibleNextSets() []uint32 {
	if x != nil {
		return x.CompatibleNextSets
	}
	return nil
}

func (x *ServerSegmentSet) GetSegments() []*ServerSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type ClientSegment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegmentId   uint32        `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Subsegments []*Subsegment `protobuf:"bytes,2,rep,name=subsegments,proto3" json:"subsegments,omitempty"` // TODO: add metadata
}

func (x *ClientSegment) Reset() {
	*x = ClientSegment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSegment) ProtoMessage() {}

func (x *ClientSegment) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSegment.ProtoReflect.Descriptor instead.
func (*ClientSegment) Descriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{4}
}

func (x *ClientSegment) GetSegmentId() uint32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *ClientSegment) GetSubsegments() []*Subsegment {
	if x != nil {
		return x.Subsegments
	}
	return nil
}

type ServerSegment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegmentId   uint32        `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Subsegments []*Subsegment `protobuf:"bytes,2,rep,name=subsegments,proto3" json:"subsegments,omitempty"`
}

func (x *ServerSegment) Reset() {
	*x = ServerSegment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSegment) ProtoMessage() {}

func (x *ServerSegment) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSegment.ProtoReflect.Descriptor instead.
func (*ServerSegment) Descriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{5}
}

func (x *ServerSegment) GetSegmentId() uint32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *ServerSegment) GetSubsegments() []*Subsegment {
	if x != nil {
		return x.Subsegments
	}
	return nil
}

type Subsegment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Subsegment_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.negotiation.Subsegment_Type" json:"type,omitempty"`
	// optional, depends on subsegment type
	Link *Link `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	// optional, depends on subsegment type
	Reference uint32 `protobuf:"varint,3,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *Subsegment) Reset() {
	*x = Subsegment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subsegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subsegment) ProtoMessage() {}

func (x *Subsegment) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subsegment.ProtoReflect.Descriptor instead.
func (*Subsegment) Descriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{6}
}

func (x *Subsegment) GetType() Subsegment_Type {
	if x != nil {
		return x.Type
	}
	return Subsegment_LINK
}

func (x *Subsegment) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *Subsegment) GetReference() uint32 {
	if x != nil {
		return x.Reference
	}
	return 0
}

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Egress  *Interface `protobuf:"bytes,1,opt,name=egress,proto3" json:"egress,omitempty"`
	Ingress *Interface `protobuf:"bytes,2,opt,name=ingress,proto3" json:"ingress,omitempty"` // TODO: add metadata
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{7}
}

func (x *Link) GetEgress() *Interface {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *Link) GetIngress() *Interface {
	if x != nil {
		return x.Ingress
	}
	return nil
}

type Interface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsdAs uint64 `protobuf:"varint,1,opt,name=isd_as,json=isdAs,proto3" json:"isd_as,omitempty"`
	Id    uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Interface) Reset() {
	*x = Interface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_negotiation_negotiation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_src_proto_negotiation_negotiation_proto_rawDescGZIP(), []int{8}
}

func (x *Interface) GetIsdAs() uint64 {
	if x != nil {
		return x.IsdAs
	}
	return 0
}

func (x *Interface) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_src_proto_negotiation_negotiation_proto protoreflect.FileDescriptor

var file_src_proto_negotiation_negotiation_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x67, 0x6f,
	0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x12,
	0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x46, 0x0a, 0x0c, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x52, 0x0b, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x73, 0x22, 0x5a, 0x0a, 0x10, 0x4e, 0x65,
	0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x46,
	0x0a, 0x0c, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x67,
	0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x74, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73,
	0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65,
	0x5f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x12, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x4e, 0x65, 0x78, 0x74,
	0x53, 0x65, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e,
	0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x30,
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x65, 0x78,
	0x74, 0x5f, 0x73, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x12, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x74, 0x73,
	0x12, 0x3c, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x67, 0x6f, 0x74,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x6f,
	0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x3f,
	0x0a, 0x0b, 0x73, 0x75, 0x62, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x67, 0x6f,
	0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x6f, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x3f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x67,
	0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0xb0, 0x01, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x36, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65,
	0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x22, 0x1f, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49,
	0x4e, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x46, 0x45, 0x52, 0x45, 0x4e, 0x43,
	0x45, 0x10, 0x01, 0x22, 0x74, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x34, 0x0a, 0x06, 0x65,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x06, 0x65, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x36, 0x0a, 0x07, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x67, 0x6f, 0x74,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x52, 0x07, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x32, 0x0a, 0x09, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x64, 0x5f, 0x61, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x73, 0x64, 0x41, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x32, 0x77, 0x0a,
	0x12, 0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x11, 0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x67,
	0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x62, 0x6c, 0x61, 0x72, 0x65, 0x72, 0x2f, 0x73, 0x63, 0x69,
	0x6f, 0x6e, 0x2d, 0x69, 0x70, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x67,
	0x6f, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_negotiation_negotiation_proto_rawDescOnce sync.Once
	file_src_proto_negotiation_negotiation_proto_rawDescData = file_src_proto_negotiation_negotiation_proto_rawDesc
)

func file_src_proto_negotiation_negotiation_proto_rawDescGZIP() []byte {
	file_src_proto_negotiation_negotiation_proto_rawDescOnce.Do(func() {
		file_src_proto_negotiation_negotiation_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_negotiation_negotiation_proto_rawDescData)
	})
	return file_src_proto_negotiation_negotiation_proto_rawDescData
}

var file_src_proto_negotiation_negotiation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_proto_negotiation_negotiation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_src_proto_negotiation_negotiation_proto_goTypes = []interface{}{
	(Subsegment_Type)(0),       // 0: proto.negotiation.Subsegment.Type
	(*NegotiationRequest)(nil), // 1: proto.negotiation.NegotiationRequest
	(*NegotiationReply)(nil),   // 2: proto.negotiation.NegotiationReply
	(*ClientSegmentSet)(nil),   // 3: proto.negotiation.ClientSegmentSet
	(*ServerSegmentSet)(nil),   // 4: proto.negotiation.ServerSegmentSet
	(*ClientSegment)(nil),      // 5: proto.negotiation.ClientSegment
	(*ServerSegment)(nil),      // 6: proto.negotiation.ServerSegment
	(*Subsegment)(nil),         // 7: proto.negotiation.Subsegment
	(*Link)(nil),               // 8: proto.negotiation.Link
	(*Interface)(nil),          // 9: proto.negotiation.Interface
}
var file_src_proto_negotiation_negotiation_proto_depIdxs = []int32{
	3,  // 0: proto.negotiation.NegotiationRequest.segment_sets:type_name -> proto.negotiation.ClientSegmentSet
	4,  // 1: proto.negotiation.NegotiationReply.segment_sets:type_name -> proto.negotiation.ServerSegmentSet
	5,  // 2: proto.negotiation.ClientSegmentSet.segments:type_name -> proto.negotiation.ClientSegment
	6,  // 3: proto.negotiation.ServerSegmentSet.segments:type_name -> proto.negotiation.ServerSegment
	7,  // 4: proto.negotiation.ClientSegment.subsegments:type_name -> proto.negotiation.Subsegment
	7,  // 5: proto.negotiation.ServerSegment.subsegments:type_name -> proto.negotiation.Subsegment
	0,  // 6: proto.negotiation.Subsegment.type:type_name -> proto.negotiation.Subsegment.Type
	8,  // 7: proto.negotiation.Subsegment.link:type_name -> proto.negotiation.Link
	9,  // 8: proto.negotiation.Link.egress:type_name -> proto.negotiation.Interface
	9,  // 9: proto.negotiation.Link.ingress:type_name -> proto.negotiation.Interface
	1,  // 10: proto.negotiation.NegotiationService.NegotiateSegments:input_type -> proto.negotiation.NegotiationRequest
	2,  // 11: proto.negotiation.NegotiationService.NegotiateSegments:output_type -> proto.negotiation.NegotiationReply
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_src_proto_negotiation_negotiation_proto_init() }
func file_src_proto_negotiation_negotiation_proto_init() {
	if File_src_proto_negotiation_negotiation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_negotiation_negotiation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NegotiationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_negotiation_negotiation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NegotiationReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_negotiation_negotiation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSegmentSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_negotiation_negotiation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSegmentSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_negotiation_negotiation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSegment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_negotiation_negotiation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerSegment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_negotiation_negotiation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subsegment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_negotiation_negotiation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_negotiation_negotiation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_negotiation_negotiation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_negotiation_negotiation_proto_goTypes,
		DependencyIndexes: file_src_proto_negotiation_negotiation_proto_depIdxs,
		EnumInfos:         file_src_proto_negotiation_negotiation_proto_enumTypes,
		MessageInfos:      file_src_proto_negotiation_negotiation_proto_msgTypes,
	}.Build()
	File_src_proto_negotiation_negotiation_proto = out.File
	file_src_proto_negotiation_negotiation_proto_rawDesc = nil
	file_src_proto_negotiation_negotiation_proto_goTypes = nil
	file_src_proto_negotiation_negotiation_proto_depIdxs = nil
}
