// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package negotiation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NegotiationServiceClient is the client API for NegotiationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NegotiationServiceClient interface {
	Negotiate(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type negotiationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNegotiationServiceClient(cc grpc.ClientConnInterface) NegotiationServiceClient {
	return &negotiationServiceClient{cc}
}

func (c *negotiationServiceClient) Negotiate(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/proto.negotiation.NegotiationService/Negotiate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NegotiationServiceServer is the server API for NegotiationService service.
// All implementations must embed UnimplementedNegotiationServiceServer
// for forward compatibility
type NegotiationServiceServer interface {
	Negotiate(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedNegotiationServiceServer()
}

// UnimplementedNegotiationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNegotiationServiceServer struct {
}

func (UnimplementedNegotiationServiceServer) Negotiate(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Negotiate not implemented")
}
func (UnimplementedNegotiationServiceServer) mustEmbedUnimplementedNegotiationServiceServer() {}

// UnsafeNegotiationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NegotiationServiceServer will
// result in compilation errors.
type UnsafeNegotiationServiceServer interface {
	mustEmbedUnimplementedNegotiationServiceServer()
}

func RegisterNegotiationServiceServer(s grpc.ServiceRegistrar, srv NegotiationServiceServer) {
	s.RegisterService(&NegotiationService_ServiceDesc, srv)
}

func _NegotiationService_Negotiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegotiationServiceServer).Negotiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.negotiation.NegotiationService/Negotiate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegotiationServiceServer).Negotiate(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// NegotiationService_ServiceDesc is the grpc.ServiceDesc for NegotiationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NegotiationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.negotiation.NegotiationService",
	HandlerType: (*NegotiationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Negotiate",
			Handler:    _NegotiationService_Negotiate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/negotiation/negotiation.proto",
}
